# Generated by Django 4.1.7 on 2023-04-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clothes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100, verbose_name="Food Name")),
                (
                    "catogiry",
                    models.CharField(
                        choices=[
                            ("WomenWare", "WomenWare"),
                            ("Kidsware", "Kidsware"),
                            ("Menware", "Menware"),
                        ],
                        max_length=100,
                    ),
                ),
                ("pairs", models.PositiveIntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("donar_contact", models.CharField(max_length=10)),
                ("food_pick_up", models.CharField(max_length=200)),
                ("pincode", models.CharField(max_length=6)),
                ("flag", models.CharField(default=False, max_length=12)),
                ("flagreq", models.CharField(default=False, max_length=12)),
                ("donarMail", models.EmailField(default="", max_length=100)),
                ("message", models.TextField(default="", max_length=300)),
                ("ngomessage", models.TextField(default="", max_length=300)),
                ("donar_name", models.CharField(default="", max_length=200)),
                ("ngo_name", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DonarUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=200)),
                ("last_name", models.CharField(default="", max_length=200)),
                ("username", models.CharField(default="", max_length=200)),
                ("email", models.CharField(default="", max_length=200)),
                ("city", models.CharField(default="", max_length=200)),
                ("state", models.CharField(default="", max_length=200)),
                ("passcode", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Footware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Food Name")),
                (
                    "catogiry",
                    models.CharField(
                        choices=[
                            ("WomenWare", "WomenWare"),
                            ("Kidsware", "Kidsware"),
                            ("Menware", "Menware"),
                        ],
                        max_length=100,
                    ),
                ),
                ("pairs", models.PositiveIntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("donar_contact", models.CharField(max_length=10)),
                ("food_pick_up", models.CharField(max_length=200)),
                ("pincode", models.CharField(max_length=6)),
                ("flag", models.CharField(default=False, max_length=12)),
                ("flagreq", models.CharField(default=False, max_length=12)),
                ("donarMail", models.EmailField(default="", max_length=100)),
                ("message", models.TextField(default="", max_length=300)),
                ("ngomessage", models.TextField(default="", max_length=300)),
                ("donar_name", models.CharField(default="", max_length=200)),
                ("ngo_name", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Health",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drugname",
                    models.CharField(max_length=100, verbose_name="Food Name"),
                ),
                (
                    "catogiry",
                    models.CharField(
                        choices=[
                            ("Polio Drops", "Polio Drops"),
                            ("Insulin", "Insulin"),
                            ("tetanus ", "tetanus "),
                            ("Covishield vaccine ", "Covishield vaccine "),
                            ("Others ", "Others "),
                        ],
                        max_length=100,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("donar_contact", models.CharField(max_length=10)),
                ("food_pick_up", models.CharField(max_length=200)),
                ("pincode", models.CharField(max_length=6)),
                ("flag", models.CharField(default=False, max_length=12)),
                ("flagreq", models.CharField(default=False, max_length=12)),
                ("donarMail", models.EmailField(default="", max_length=100)),
                ("message", models.TextField(default="", max_length=300)),
                ("ngomessage", models.TextField(default="", max_length=300)),
                ("donar_name", models.CharField(default="", max_length=200)),
                ("ngo_name", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Users_donations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_name",
                    models.CharField(max_length=100, verbose_name="Food Name"),
                ),
                (
                    "food_type",
                    models.CharField(
                        choices=[("VEG", "VEG"), ("NON-VEG", "NON-VEG")], max_length=100
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("donar_contact", models.CharField(max_length=10)),
                ("food_pick_up", models.CharField(max_length=200)),
                ("pincode", models.CharField(max_length=6)),
                ("flag", models.CharField(default=False, max_length=12)),
                ("flagreq", models.CharField(default=False, max_length=12)),
                ("donarMail", models.EmailField(default="", max_length=100)),
                ("message", models.TextField(default="", max_length=300)),
                ("ngomessage", models.TextField(default="", max_length=300)),
                ("donar_name", models.CharField(default="", max_length=200)),
                ("ngo_name", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
