# Generated by Django 4.1.7 on 2023-03-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_health"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Food Name")),
                (
                    "catogiry",
                    models.CharField(
                        choices=[
                            ("WomenWare", "WomenWare"),
                            ("Kidsware", "Kidsware"),
                            ("Menware", "Menware"),
                        ],
                        max_length=100,
                    ),
                ),
                ("pairs", models.PositiveIntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("donar_contact", models.CharField(max_length=10)),
                ("food_pick_up", models.CharField(max_length=200)),
                ("pincode", models.CharField(max_length=6)),
                ("flag", models.CharField(default=False, max_length=12)),
                ("flagreq", models.CharField(default=False, max_length=12)),
                ("donarMail", models.EmailField(default="", max_length=100)),
                ("message", models.TextField(default="", max_length=300)),
                ("ngomessage", models.TextField(default="", max_length=300)),
                ("donar_name", models.CharField(default="", max_length=200)),
                ("ngo_name", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="health",
            name="catogiry",
            field=models.CharField(
                choices=[
                    ("Polio Drops", "Polio Drops"),
                    ("Insulin", "Insulin"),
                    ("tetanus ", "tetanus "),
                    ("Covishield vaccine ", "Covishield vaccine "),
                ],
                max_length=100,
            ),
        ),
    ]
