# Generated by Django 4.1.5 on 2023-01-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, default=False, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="dd_email",
            field=models.EmailField(
                default=False, max_length=100, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dd_username",
            field=models.CharField(
                blank=True,
                default=False,
                max_length=100,
                null=True,
                verbose_name="User Name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="donation_from",
            field=models.CharField(
                choices=[
                    ("1", "Restaurent"),
                    ("2", "Mess"),
                    ("3", "Hotel"),
                    ("4", "Hostel"),
                    ("5", "Events"),
                    ("6", "Donation"),
                    ("7", "Other"),
                ],
                default=True,
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pincode",
            field=models.CharField(default=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_Donar",
            field=models.BooleanField(verbose_name="Donar"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_NGO",
            field=models.BooleanField(verbose_name="NGO"),
        ),
    ]
