# Generated by Django 4.1.7 on 2023-02-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users_donations",
            name="donarMail",
            field=models.EmailField(default="", max_length=100),
        ),
    ]
