# Generated by Django 4.1.5 on 2023-02-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food_requests",
            name="username",
        ),
    ]
