# Generated by Django 4.1.5 on 2023-01-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_address_user_city_user_dd_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="dd_email",
            field=models.EmailField(default="", max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="dd_username",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                null=True,
                verbose_name="User Name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.IntegerField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="pincode",
            field=models.CharField(default="", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
    ]
