# Generated by Django 4.1.7 on 2023-02-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_users_donations_ngomessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="users_donations",
            name="flagreq",
            field=models.CharField(default=False, max_length=12),
        ),
    ]
