# Generated by Django 4.1.5 on 2023-01-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_rename_ud_username_users_donations_food_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users_donations",
            name="food_name",
            field=models.CharField(max_length=100, verbose_name="Food Name"),
        ),
    ]
