# Generated by Django 4.1.7 on 2023-04-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DonarUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("passcode", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Users_donations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "food_type",
                    models.CharField(
                        choices=[("VEG", "VEG"), ("NON-VEG", "NON-VEG")], max_length=100
                    ),
                ),
                (
                    "medine_type",
                    models.CharField(
                        choices=[("Polio", "Polio"), ("Others", "Others")],
                        max_length=100,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=100
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default="")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("exp", models.DateTimeField()),
                ("contact", models.CharField(max_length=10)),
                ("pick_up", models.CharField(max_length=200)),
                ("pincode", models.CharField(max_length=6)),
                ("donar_name", models.CharField(default="", max_length=200)),
                ("flag", models.CharField(default=False, max_length=12)),
                ("flagreq", models.CharField(default=False, max_length=12)),
                ("donarMail", models.EmailField(default="", max_length=100)),
                ("message", models.TextField(default="", max_length=300)),
                ("ngomessage", models.TextField(default="", max_length=300)),
            ],
        ),
    ]
