# Generated by Django 4.1.7 on 2023-04-11 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users_donations",
            name="donarMail",
        ),
        migrations.RemoveField(
            model_name="users_donations",
            name="flagreq",
        ),
        migrations.RemoveField(
            model_name="users_donations",
            name="message",
        ),
        migrations.RemoveField(
            model_name="users_donations",
            name="ngomessage",
        ),
    ]
