# Generated by Django 4.1.7 on 2023-02-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_Donar",
            field=models.BooleanField(default=False, verbose_name="Donar"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_NGO",
            field=models.BooleanField(default=False, verbose_name="NGO"),
        ),
    ]
