# Generated by Django 4.1.7 on 2023-02-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_is_donar_alter_user_is_ngo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users_donations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_name",
                    models.CharField(max_length=100, verbose_name="Food Name"),
                ),
                (
                    "food_type",
                    models.CharField(
                        choices=[("VEG", "VEG"), ("NON-VEG", "NON-VEG")], max_length=100
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("donar_contact", models.CharField(max_length=10)),
                ("food_pick_up", models.CharField(max_length=200)),
                ("pincode", models.CharField(max_length=6)),
                ("flag", models.CharField(default=False, max_length=12)),
                ("flagreq", models.CharField(default=False, max_length=12)),
                ("donarMail", models.EmailField(default="", max_length=100)),
                ("message", models.TextField(default="", max_length=300)),
                ("ngomessage", models.TextField(default="", max_length=300)),
                ("donar_name", models.CharField(default="", max_length=200)),
                ("ngo_name", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
