# Generated by Django 4.1.7 on 2023-04-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_users_donations_donarmail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users_donations",
            name="exp",
            field=models.DateTimeField(default=""),
        ),
    ]
