# Generated by Django 4.1.7 on 2023-03-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
