# Generated by Django 4.1.7 on 2023-03-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_book"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
    ]
