# Generated by Django 4.1.7 on 2023-04-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_users_donations_exp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users_donations",
            name="exp",
            field=models.DateTimeField(),
        ),
    ]
