# Generated by Django 4.1.7 on 2023-04-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_users_donations_exp"),
    ]

    operations = [
        migrations.AddField(
            model_name="donaruser",
            name="confirm_password",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="donaruser",
            name="new_password",
            field=models.CharField(default="", max_length=200),
        ),
    ]
