# Generated by Django 4.1.7 on 2023-05-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=30)),
                (
                    "options",
                    models.CharField(
                        choices=[
                            ("is_Donar", "is_Donar"),
                            ("is_Volunteer", "is_Volunteer"),
                        ],
                        default=False,
                        max_length=100,
                    ),
                ),
                (
                    "gander",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                        ],
                        default=False,
                        max_length=100,
                    ),
                ),
                (
                    "passcode",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                        ],
                        default=False,
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("credits", models.PositiveIntegerField(default=100)),
                ("linkedin_token", models.TextField(blank=True, default="")),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Users_donations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "food_type",
                    models.CharField(
                        choices=[("VEG", "VEG"), ("NON-VEG", "NON-VEG")], max_length=100
                    ),
                ),
                (
                    "medine_type",
                    models.CharField(
                        choices=[("Polio", "Polio"), ("Others", "Others")],
                        max_length=100,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=100
                    ),
                ),
                ("quantity", models.CharField(default="0", max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("exp", models.DateTimeField()),
                ("contact", models.CharField(max_length=10)),
                ("pick_up", models.CharField(max_length=200)),
                ("pincode", models.CharField(max_length=6)),
                ("donar_name", models.CharField(default="", max_length=200)),
                ("flag", models.CharField(default=False, max_length=12)),
            ],
        ),
    ]
