# Generated by Django 4.1.7 on 2023-05-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="credits",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="linkedin_token",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="passcode",
        ),
    ]
