# Generated by Django 4.1.7 on 2023-05-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_myuser_credits_remove_myuser_expiry_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="AreaOfInterest",
            field=models.CharField(
                choices=[
                    ("Scribes", "Scribes"),
                    ("AnimalHusbandry", "AnimalHusbandry"),
                    ("MedicalCamp", "MedicalCamp"),
                    ("Devilery", "Devilery"),
                ],
                default=False,
                max_length=100,
            ),
        ),
    ]
