# Generated by Django 4.1.7 on 2023-05-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_myuser_areaofinterest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myuser",
            old_name="gander",
            new_name="gendar",
        ),
    ]
