# Generated by Django 4.1.7 on 2023-05-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_gander_myuser_gendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalCampModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Organisername", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("for dogs", "for dogs"),
                            ("for Goats and sheeps", " for Goats and sheeps"),
                            ("for cattles", "for cattles "),
                            ("for birds", "for birds"),
                            ("for all", "for all"),
                        ],
                        max_length=100,
                    ),
                ),
                ("place", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("camp_starts_at", models.CharField(max_length=100)),
                ("camp_ends_at", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("contact", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Bloodcamp_event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Organisername", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("camp_starts_at", models.CharField(max_length=100)),
                ("camp_ends_at", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("contact", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CBEmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Organisername", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("festivals", "festivals"),
                            ("fairs", "fairs"),
                            ("cultural celebrations", "cultural celebrations "),
                        ],
                        max_length=50,
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("camp_starts_at", models.CharField(max_length=100)),
                ("camp_ends_at", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("contact", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Educational_event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Organisername", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("workshops", "workshops"),
                            ("training sessions", "training sessions"),
                            ("classes", "classes "),
                            ("job_mela", "job_mela"),
                        ],
                        max_length=50,
                    ),
                ),
                ("Topic", models.CharField(max_length=100)),
                ("eligibility", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("camp_starts_at", models.CharField(max_length=100)),
                ("camp_ends_at", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("contact", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ForScribersModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Organisername", models.CharField(max_length=100)),
                ("purpose", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("camp_starts_at", models.CharField(max_length=100)),
                ("camp_ends_at", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("contacts", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalCamp_event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Organiser_name", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("camp_starts_at", models.CharField(max_length=100)),
                ("camp_ends_at", models.CharField(max_length=100)),
                ("Date", models.DateField()),
                ("contact_no", models.CharField(max_length=100)),
                (
                    "For_whom",
                    models.CharField(
                        choices=[
                            ("Children", "Children"),
                            ("middle age", "middle age"),
                            ("old age", "old age"),
                            ("all", "all"),
                        ],
                        max_length=100,
                    ),
                ),
                ("facilities", models.CharField(max_length=500)),
                ("message", models.CharField(max_length=100)),
            ],
        ),
    ]
