# Generated by Django 4.1.7 on 2023-05-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_medicalcamp_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalcampmodel",
            name="date",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="bloodcamp_event",
            name="date",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="cbemodel",
            name="date",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="educational_event",
            name="date",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="forscribersmodel",
            name="date",
            field=models.CharField(max_length=100),
        ),
    ]
